version: '2'

services:
  #traefik:
  #  image: traefik:1.6-alpine
  #  restart: always
  #  container_name: traefik
  #  ports:
  #    - 80:80
  #    - 443:443
  #  labels:
  #    - traefik.enable=true
  #    - traefik.frontend.rule=Host:traefik.idp.carehybrid.com
  #    - traefik.port=8081
  #    - traefik.docker.network=web
  #  networks:
  #    - web
  #  volumes:
  #    - /var/run/docker.sock:/var/run/docker.sock
  #    - /opt/traefik/traefik.toml:/traefik.toml
  #    - /opt/traefik/acme.json:/acme.json
  tomcat:
    container_name: tomcat
    image: cloudesire/tomcat:8-jre8
    restart: always
    ports:
      - "8080:8080"
      - "8000:8000"
      - "8443:8443"
    environment:
      - CATALINA_OPTS=-Xms512M -Xmx1024M -XX:MaxPermSize=512m
     # - JAVA_OPTS=-Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=8000
      - TOMCAT_PASS=C1sco123=
    volumes:
   #   - /opt/traefik/acme.json:/etc/letsencrypt/acme/acme.json
      - /opt/tomcat/webapps:/tomcat/webapps
      - /opt/tomcat/conf:/tomcat/conf
      - /opt/tomcat/certs:/tomcat/certs
      - /opt/cas/etc/cas:/etc/cas
    networks:
      - web
    #labels:
    #  - traefik.enable=true
    #  - traefik.frontend.rule=Host:sso.idp.carehybrid.com
    #  - traefik.port=8443
    #  - traefik.docker.network=web
  maven:
    container_name: maven
    image: maven:3.5-jdk-9
    restart: always
    volumes:
      - /opt/tomcat/webapps:/tomcat/webapps
      - /opt/cas/etc/cas:/etc/cas
      - /opt/cas/git:/cas/git
    networks:
      - web
    command: tail -F anything
networks:
  web:
    external: true
